version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/RandLProject
      - spring.datasource.username=root
      - spring.datasource.password=satoaki
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=satoaki
      - MYSQL_PASSWORD=satoaki
      - MYSQL_USER=satoaki
      - MYSQL_DATABASES=aaa

volumes:
  db-data:
